### ISSUE TITLE
Update peer dependencies to match ^2.x.x

### ISSUE THREAD

**Issue by luii** [ahaasler/tailwindcss-material#1]
Since `tailwindcss` adheres to SemVer there should be no problem to include Minor Features and Patches into your `peerDependencies` on line [47](https://github.com/ahaasler/tailwindcss-material/blob/main/package.json#L47). I don't think that `tailwindcss` will change anything until JIT is released.

**Comment by ahaasler** [comment]
Thanks for noticing, it should be fixed in 1.0.1, but something is failing on the publish action, I'll check tomorrow.

**Comment by ahaasler** [comment]
Released https://github.com/ahaasler/tailwindcss-material/releases/tag/v1.0.1
